In [1]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


In [3]:
myList=[1,2,3,4]
stringList=['apple','orange']

In [4]:
print(myList)

[1, 2, 3, 4]


In [5]:
print(stringList)

['apple', 'orange']


In [6]:
type(myList)

list

In [10]:
#dir(np)

In [8]:
arr = np.array(myList)

In [9]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#shape of the array
arr.shape

(4,)

In [12]:
arr.size

4

In [16]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])

In [14]:
type(arr)

numpy.ndarray

In [17]:
arr.shape

(3, 5)

In [18]:
arr.size


15

In [19]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
#numpy array indexing

my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [22]:
print(arr[0])

1


In [23]:
#print second element from the above array
print(arr[1])

2


In [27]:
print(" Third and Fourth element is", arr[2],arr[3])

 Third and Fourth element is 3 4


In [28]:
#Access 2D array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])

In [29]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [30]:
print(arr[0:1])

[[1 2 3 4 5]]


In [31]:
arr[0,2]

3

In [33]:
print('Seconmd element on 1st row: ',arr[0,1])

Seconmd element on 1st row:  2


In [34]:
#Access the element on second row , 5th column:
arr[1,4]

6

In [4]:
valArr= np.array([[1,2,3],[4,5,6]])

In [8]:
print('Printing the variables :',valArr)
print('\n')
print('Size :',valArr.size,'\n')
print('Shape :',valArr.shape,'\n')
print('Indexing first row first column :',valArr[0,0],'\n')
print('Indexing second row third column :',valArr[1,2],'\n')

Printing the variables : [[1 2 3]
 [4 5 6]]


Size : 6 

Shape : (2, 3) 

Indexing first row first column : 1 

Indexing second row third column : 6 



In [8]:
#Create 5X5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print('Printing the variables :','\n',newArr)
print('\n')
print('Size :',newArr.size,'\n')
print('Shape :',newArr.shape,'\n')
print('Indexing 2nd element third row :',newArr[2,1],'\n')
print('Indexing 1st element on 4th row :',newArr[3,0],'\n')

Printing the variables : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Size : 25 

Shape : (5, 5) 

Indexing 2nd element third row : 12 

Indexing 1st element on 4th row : 16 



In [12]:
#negative indexing

# myList = [1,2,3,4,5]
# arr = np.array(myList)

# print(arr)

valArr= np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [13]:
valArr[1,-1] # 2nd row last element

6

In [15]:
valArr[0,-1] # 1st row last element

3

In [ ]:
#numPy Array slicing